# Generated by Django 4.1.7 on 2023-04-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateTimeField(auto_now_add=True, verbose_name='Login Date')),
                ('login_time', models.TimeField(verbose_name='Login Time')),
                ('logout_time', models.TimeField(verbose_name='Logout Time')),
                ('break_start_time', models.TimeField(verbose_name='Break Start Time')),
                ('break_end_time', models.TimeField(verbose_name='Break End Time')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('staffcode', models.CharField(choices=[('AUTO', 'Auto'), ('Custom', 'Custom')], default='AUTO', max_length=50, verbose_name='Staff Code Type')),
                ('office_hour_start', models.TimeField(verbose_name='Office hour start')),
                ('office_hour_end', models.TimeField(verbose_name='Office hour end')),
                ('access_network', models.CharField(max_length=50, verbose_name='Access Network')),
                ('probablation_peroid', models.CharField(choices=[('1', '1 months'), ('3', '3 Months'), ('6', '6 Months')], default=3, max_length=50, verbose_name='Probablation Peroid')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('mobilenumber', models.IntegerField(verbose_name='Mobile number')),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Employee Email')),
                ('dateofbirth', models.DateField(verbose_name='Date of Birth')),
                ('salary_type', models.CharField(choices=[('calendar', 'Calendar Days'), ('30day', '30 Days')], max_length=50, verbose_name='Salary Type')),
                ('salary_amount', models.IntegerField(default=1400, verbose_name='Salary Amount')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('duty_time', models.TimeField(verbose_name='Duty Time')),
                ('working_hours', models.DurationField(verbose_name='Working Hours')),
                ('overtime_ratio', models.IntegerField(default=0, verbose_name='Overtime Ratio')),
                ('allowlateby', models.DurationField(verbose_name='Allow late by')),
                ('allowance', models.FloatField(blank=True, null=True, verbose_name='Allowance')),
                ('casual_leave', models.IntegerField(default=0, verbose_name='Casual Leave Days')),
                ('staffcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Code')),
                ('is_active_emp', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Leave Name')),
                ('leave_date', models.DateField(verbose_name='Leave Date')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sickleavedays', to='hajir.company')),
            ],
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField(verbose_name='Total Leave Days')),
                ('leave_by', models.CharField(choices=[('m', 'Monthly'), ('w', 'Weekly'), ('y', 'Yearly')], default='m', max_length=50, verbose_name='Leave By')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sickleave', to='hajir.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='hajir.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hajir.employee', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Leave Name')),
                ('leave_date', models.DateField(verbose_name='Leave Date')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov', to='hajir.company')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default=1, max_length=50, null=True, verbose_name='Day')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hajir.company')),
            ],
        ),
    ]
