# Generated by Django 4.1.7 on 2023-04-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default=1, max_length=50, verbose_name='Day')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Leave Name')),
                ('leave_date', models.DateField(verbose_name='Leave Date')),
            ],
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField(verbose_name='Total Leave Days')),
                ('leave_by', models.CharField(choices=[('m', 'Monthly'), ('w', 'Weekly'), ('y', 'Yearly')], default='m', max_length=50, verbose_name='Leave By')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Leave Name')),
                ('leave_date', models.DateField(verbose_name='Leave Date')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('staffcode', models.CharField(choices=[('AUTO', 'Auto'), ('Custom', 'Custom')], default='AUTO', max_length=50, verbose_name='Staff Code Type')),
                ('office_hour_start', models.CharField(max_length=50, verbose_name='Office hour start')),
                ('office_hour_end', models.CharField(max_length=50, verbose_name='Office hour end')),
                ('access_network', models.CharField(max_length=50, verbose_name='Access Network')),
                ('probablation_peroid', models.CharField(choices=[(1, '1 months'), (3, '3 Months'), (6, '6 Months')], default=3, max_length=50, verbose_name='Probablation Peroid')),
                ('business_leave_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hajir.businessleavedays')),
                ('special_leave_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hajir.specialleavedays', verbose_name='')),
            ],
        ),
    ]
