# Generated by Django 4.1.7 on 2023-04-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hajir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentleavedays',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov', to='hajir.company'),
        ),
        migrations.AddField(
            model_name='specialleavedays',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='hajir.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='special_leave_days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hajir.specialleavedays', verbose_name='special leave'),
        ),
    ]
