# Generated by Django 4.1.7 on 2023-04-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hajir', '0002_governmentleavedays_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sick_leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hajir.sickleave', verbose_name=''),
        ),
    ]
