# Generated by Django 4.1.7 on 2023-04-22 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hajir', '0002_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee User'),
        ),
    ]
