# Generated by Django 4.1.7 on 2023-04-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hajir', '0003_company_sick_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessleavedays',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hajir.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sick_leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hajir.sickleave', verbose_name='sick leave'),
        ),
    ]
