# Generated by Django 4.1.7 on 2023-04-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_customuser_email_alter_customuser_gps_and_more'),
        ('hajir', '0003_remove_employee_company_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentleavedays',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='specialleavedays',
            name='company_name',
        ),
        migrations.AddField(
            model_name='businessleavedays',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hajir.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Employee Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active_emp',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sickleave', to='hajir.company'),
        ),
        migrations.AddField(
            model_name='specialleavedays',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sickleavedays', to='hajir.company'),
        ),
        migrations.AlterField(
            model_name='businessleavedays',
            name='day',
            field=models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default=1, max_length=50, null=True, verbose_name='Day'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='hajir.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hajir.employee', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50, verbose_name='Employer Name')),
                ('employers', models.ManyToManyField(to='hajir.company', verbose_name='Copmany Employers')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('employers', models.ManyToManyField(to='hajir.company', verbose_name='Copmany Employers')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hajir.employeeuser', verbose_name='Employee User'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hajir.company', verbose_name='EmployeCompany'),
        ),
    ]
