# Generated by Django 4.1.7 on 2023-04-22 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hajir', '0004_alter_invitations_options_company_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_approvers',
            field=models.IntegerField(default=0, verbose_name='Total Approvers'),
        ),
        migrations.AddField(
            model_name='company',
            name='total_employees',
            field=models.IntegerField(default=0, verbose_name='Total Employees'),
        ),
        migrations.AddField(
            model_name='invitations',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
