# Generated by Django 4.1.7 on 2023-04-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hajir', '0008_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Leave Name')),
                ('leave_date', models.DateField(verbose_name='Leave Date')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyleavedays', to='hajir.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='specialleavedays',
            name='company',
        ),
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hajir.company', verbose_name='AttendanceCompany'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='login_date',
            field=models.DateTimeField(verbose_name='Login Date'),
        ),
        migrations.DeleteModel(
            name='GovernmentLeaveDays',
        ),
        migrations.DeleteModel(
            name='SpecialLeaveDays',
        ),
    ]
