# Generated by Django 4.1.7 on 2023-04-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hajir', '0009_leavedays_remove_specialleavedays_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentLeaveDays',
            fields=[
                ('leavedays_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hajir.leavedays')),
            ],
            bases=('hajir.leavedays',),
        ),
        migrations.CreateModel(
            name='SpecialLeaveDays',
            fields=[
                ('leavedays_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hajir.leavedays')),
            ],
            bases=('hajir.leavedays',),
        ),
    ]
