# Generated by Django 4.1.3 on 2023-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hajir', '0010_governmentleavedays_specialleavedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessleavedays',
            name='day',
            field=models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday')], default=1, max_length=50, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='company',
            name='staffcode',
            field=models.CharField(default='a', max_length=50, verbose_name='Staff Code Type'),
        ),
    ]
