# Generated by Django 4.1.5 on 2023-09-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='coupon_code',
            field=models.CharField(max_length=150, null=True, verbose_name='Coupon Code'),
        ),
    ]
