# Generated by Django 4.1.5 on 2023-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recipienttransactiontype_transactions_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipienttransactiontype',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='recipienttransactiontype',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='recipienttransactiontype',
            name='account_number',
            field=models.IntegerField(null=True, verbose_name='Account Number'),
        ),
    ]
