# Generated by Django 4.1.5 on 2023-09-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_recipienttransactiontype_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='phone')),
            ],
        ),
        migrations.AddField(
            model_name='recipienttransactiontype',
            name='recipient_transaction_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.recipient'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='recipient',
            field=models.ForeignKey(default=0, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.recipient'),
        ),
    ]
