# Generated by Django 4.1.7 on 2023-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_alter_profile_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkycForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_img', models.ImageField(upload_to='media/', verbose_name='Front Image')),
                ('back_img', models.ImageField(upload_to='media', verbose_name='Back Image')),
                ('tilted', models.ImageField(upload_to='media', verbose_name='Tilted Image')),
                ('indended_use_of_account', models.CharField(default='own_use', max_length=50, verbose_name='Indended Use of Account')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('date_of_issue', models.DateField(verbose_name='Date of issue')),
                ('peroid_of_stay', models.DateField(verbose_name='Peroid of stay')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('postal', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('prefature', models.CharField(max_length=50, verbose_name='Prefecture')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('building_name_or_number', models.CharField(max_length=50, verbose_name='Building Name/ Number')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='IntendedUseOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Indended Use of Account')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='None', max_length=50, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_type',
            field=models.CharField(default='None', max_length=100, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_back',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Passport Back'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_front',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Passport Front'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration number'),
        ),
    ]
