# Generated by Django 4.1.5 on 2023-09-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipienttransactiontype',
            old_name='recipient_transaction_type',
            new_name='recpipient',
        ),
        migrations.AlterField(
            model_name='recipienttransactiontype',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Account Number'),
        ),
    ]
