# Generated by Django 4.1.5 on 2023-09-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_recipient_transaction_type_recipienttransactiontype_recpipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipienttransactiontype',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='WalletID/Account Number'),
        ),
    ]
