# Generated by Django 4.1.7 on 2023-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ekycform_intendeduseofaccount_customuser_isverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
