# Generated by Django 4.1.7 on 2023-03-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_termsandconditions_customuser_is_business_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EkycForm',
            new_name='Ekyc',
        ),
    ]
