# Generated by Django 4.1.7 on 2023-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_ekycform_ekyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekyc',
            name='audit_report',
            field=models.FileField(null=True, upload_to='media', verbose_name='Audit Report'),
        ),
        migrations.AddField(
            model_name='ekyc',
            name='source_of_income',
            field=models.FileField(null=True, upload_to='media', verbose_name='Source of Income'),
        ),
        migrations.AddField(
            model_name='ekyc',
            name='tax_return',
            field=models.FileField(null=True, upload_to='media', verbose_name='Tax Return'),
        ),
    ]
