# Generated by Django 4.1.7 on 2023-03-11 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ekyc_audit_report_ekyc_source_of_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekyc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
