# Generated by Django 4.1.7 on 2023-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_ekyc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekyc',
            name='audit_report',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Audit Report'),
        ),
        migrations.AlterField(
            model_name='ekyc',
            name='back_img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Back Image'),
        ),
        migrations.AlterField(
            model_name='ekyc',
            name='front_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Front Image'),
        ),
        migrations.AlterField(
            model_name='ekyc',
            name='source_of_income',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Source of Income'),
        ),
        migrations.AlterField(
            model_name='ekyc',
            name='tax_return',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Tax Return'),
        ),
        migrations.AlterField(
            model_name='ekyc',
            name='tilted',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Tilted Image'),
        ),
    ]
