# Generated by Django 4.1.7 on 2023-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_ekyc_audit_report_alter_ekyc_back_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isVerified',
            new_name='emailVerified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='kycVerified',
            field=models.IntegerField(choices=[(0, 'Uniniialized'), (1, 'Pending'), (2, 'Verified')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profileVerified',
            field=models.BooleanField(default=False),
        ),
    ]
