# Generated by Django 4.1.5 on 2023-03-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_gps_ekyc_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Android'), (1, 'Ios')], default=0)),
                ('title', models.CharField(default='', max_length=20)),
                ('version', models.CharField(default='', max_length=20)),
                ('message', models.CharField(default='', max_length=255)),
                ('update_action', models.IntegerField(choices=[(1, 'Soft Update'), (2, 'Force Update'), (3, 'Maintainence')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='info.png', upload_to='media')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profession',
            name='status_of_residence',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.statusofresidence'),
        ),
    ]
