# Generated by Django 4.1.7 on 2023-03-19 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_appversion_banners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('front_img', models.ImageField(upload_to='media/', verbose_name='Front Image')),
                ('back_img', models.ImageField(upload_to='media', verbose_name='Back Image')),
                ('tilted', models.ImageField(upload_to='media', verbose_name='Tilted Image')),
                ('selfie', models.ImageField(upload_to='media', verbose_name='Selfie Image')),
                ('blink', models.ImageField(upload_to='media', verbose_name='Blink Image')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
