# Generated by Django 4.1.7 on 2023-03-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profiledocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledocuments',
            name='user',
        ),
    ]
