# Generated by Django 4.1.7 on 2023-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_currencyrate_postalcode_provincedistricts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('continent', models.CharField(max_length=50, verbose_name='Continent')),
                ('estimate', models.IntegerField(verbose_name='Estimate')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('estimate2', models.IntegerField(verbose_name='Estimate2')),
                ('year2', models.CharField(max_length=50, verbose_name='Year2')),
                ('flag_img', models.URLField(verbose_name='flag image')),
            ],
        ),
    ]
