# Generated by Django 4.1.7 on 2023-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_currencyrate_created_at_currencyrate_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='update_at',
            field=models.DateField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
