# Generated by Django 4.1.7 on 2023-04-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_currencyrate_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrate',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
