# Generated by Django 4.1.7 on 2023-04-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_update_at_currencyrate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
