# Generated by Django 4.1.7 on 2023-04-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_currencyrate_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='updated_at',
        ),
    ]
