# Generated by Django 4.1.7 on 2023-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_currencyrate_created_at_currencyrate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
    ]
