# Generated by Django 4.1.7 on 2023-04-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_currencyrate_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppVersion',
        ),
    ]
