# Generated by Django 4.1.7 on 2023-04-08 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkycType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Unverified'), (2, 'Basic'), (3, 'Full')], default=0, verbose_name='EKYC Type')),
                ('transactions_limit_per_day', models.IntegerField(verbose_name='Transactions limit per day')),
                ('transactions_limit_per_month', models.IntegerField(verbose_name='Transactions limit by month')),
                ('transactions_limit_per_six_months', models.IntegerField(verbose_name='Transactions limit by half year')),
                ('transactions_limit_per_year', models.IntegerField(verbose_name='Transactions limit by year')),
                ('transactions_amount_per_day', models.IntegerField(verbose_name='Transactions amount per day')),
                ('transactions_amount_per_month', models.IntegerField(verbose_name='Transactions amount by month')),
                ('transactions_amount_per_six_months', models.IntegerField(verbose_name='Transactions amount by half year')),
                ('transactions_amount_per_year', models.IntegerField(verbose_name='Transactions amount by year')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(0, 'Credit Card'), (2, 'Bank'), (3, 'Cash'), (4, 'Wallet')], verbose_name='Transactions type')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('account_number', models.IntegerField(verbose_name='Account Number')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(verbose_name='Transaction Amount')),
                ('charge_amount', models.FloatField(verbose_name='Transaction Amount')),
                ('remarks', models.CharField(max_length=150, verbose_name='Remarks')),
                ('transaction_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_send', to=settings.AUTH_USER_MODEL, verbose_name='from')),
                ('transaction_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_received', to=settings.AUTH_USER_MODEL, verbose_name='to')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transactiontype', verbose_name='')),
            ],
        ),
    ]
