# Generated by Django 4.1.7 on 2023-04-08 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_ekyctype_transactiontype_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ekyctype', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transactiontype'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
