# Generated by Django 4.1.7 on 2023-04-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_customuser_kyc_type_alter_transactions_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ekyctype'),
        ),
        migrations.AlterField(
            model_name='ekyctype',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unverified'), (2, 'Basic'), (3, 'Full')], default=0, verbose_name='EKYC Type'),
        ),
    ]
