# Generated by Django 4.1.7 on 2023-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_customuser_kyc_type_alter_ekyctype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=True, verbose_name='IsEmployee'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='IsEmployer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_user',
            field=models.BooleanField(default=True, verbose_name='Wallet User'),
        ),
    ]
