# Generated by Django 4.1.7 on 2023-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_customuser_is_employee_customuser_is_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='no@mail.com', max_length=100, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gps',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kycVerified',
            field=models.IntegerField(choices=[(0, 'Uninitialized'), (1, 'Pending'), (2, 'Verified')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_user',
            field=models.BooleanField(default=False, verbose_name='Wallet User'),
        ),
    ]
