# Generated by Django 4.1.5 on 2023-09-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_rps_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepalbankaccount',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=60, unique=True),
        ),
    ]
